version: '3'

services:
  web:
    image: camera_manager_be:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camera_manager_be
    #    command: "uwsgi --ini /app/camera/wsgi/uwsgi.ini"
    command: "gunicorn camera.wsgi -c /app/camera/wsgi/gunicorn.conf.py"
    network_mode: host
    restart: always
    volumes:
      - ./static:/app/static/
      - ./media:/app/media/

  beat:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: "celery -A camera beat --loglevel=info"
    network_mode: host

  worker:
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    restart: always
    command: "celery -A camera worker --loglevel=info"
    network_mode: host

  nginx:
    image: nginx:latest
    container_name: production_nginx
    network_mode: "host"
    restart: always
    volumes:
      - .:/camera
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d

  redis:
    image: "redis:alpine"
    container_name: cache
    ports:
      - "6379:6379"
